changelog:
  categories:
    - title: "🎉 New Features"
      labels:
        - feature
        - epic

    - title: "❤️ Improvements"
      labels:
        - enhancement

    - title: "🛠️ Bugfixes"
      labels:
        - bug
