[tool.poetry]
name = "ayon-server"
version = "1.0.1"
description = ""
authors = ["Ynput <info@ynput.io>"]

[tool.poetry.dependencies]
python = "^3.10"
aiofiles = "^23.2.1"
aioshutil = "^1.3"
asyncpg = "^0.29.0"
codenamize = "^1.2.3"
email-validator = "^1.1.3"
fastapi = "^0.106"
geoip2 = "^4.8.0"
gunicorn = "^21.2"
httpx = "^0.26"
nxtools = "^1.6"
orjson = "^3.8.6"
psutil = "^5.9.4"
pydantic = "1.10.12" # 1.10.12 is the last 1.x version
pyyaml = "^6.0.1"
redis = "^5.0.1"
rich = "^13.4.2"
shortuuid = "^1.0.11"
strawberry-graphql = {extras = ["fastapi"], version = "^0.217.0"}
toml = "^0.10.2"
types-toml = "^0.10.8"
user-agents = "^2.2.0"
uvicorn = {extras = ["standard"], version = "^0.25"}
semver = "^3.0.1"
pyjwt = "^2.8.0"
cryptography = "^41.0.7"
rez="^2.114"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
pytest-order = "^1.0.1"
ruff = "^0.1.9"
black = {version = "^22.1.0", allow-prereleases = true}
mypy = "^1.8"
pre-commit = "^2.20.0"


[tool.ruff]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "C",   # flake8-comprehensions
    # "B",   # flake8-bugbear
    "ISC", # flake8-implicit-str-concat
    "C4",  # flake8-comprehensions
    # "N",    # pep8-naming
    # "SIM",  # flake8-simplify
]

ignore = [
    "E501",  # line too long, handled by black
    "E721",  # do not compare types, i'll fix this later :)
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex. C'mon - this is a complex project
]

[tool.black]
line-length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

